// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OrgManager;

#nullable disable

namespace OrgManager.Migrations
{
    [DbContext(typeof(OrgDbContext))]
    [Migration("20250914153801_AddJobTitles")]
    partial class AddJobTitles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OrgManager.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1becb0c4-4852-46e8-a05d-d46c7cf8e162"),
                            Description = "need datascience dev only",
                            Name = "Data Science"
                        },
                        new
                        {
                            Id = new Guid("6ffc9a92-8266-49a0-8d3d-1b47169be295"),
                            Description = "need fullstack dev only",
                            Name = "Full Stack"
                        },
                        new
                        {
                            Id = new Guid("c26340d5-41d1-407e-95f3-e970ae41cefe"),
                            Description = "need frontend dev only",
                            Name = "Front End"
                        },
                        new
                        {
                            Id = new Guid("7ffd8a16-eb05-429d-a9a5-672229e74443"),
                            Description = "need backend dev only",
                            Name = "Back End"
                        });
                });

            modelBuilder.Entity("OrgManager.Entities.JobTitle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("MaxSalary")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MinSalary")
                        .HasColumnType("numeric");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("JobTitles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2da23649-4f66-4ec4-8623-e9d009aecbd1"),
                            Description = "Develops and maintains software applications",
                            MaxSalary = 150000m,
                            MinSalary = 75000m,
                            Title = "Software Engineer"
                        },
                        new
                        {
                            Id = new Guid("4622e91c-8569-43ce-bcb0-3b417cee0d77"),
                            Description = "Leads software development projects and mentors junior developers",
                            MaxSalary = 180000m,
                            MinSalary = 100000m,
                            Title = "Senior Software Engineer"
                        },
                        new
                        {
                            Id = new Guid("15f7d068-66d9-4b83-a0b9-4f4db8ffd5a2"),
                            Description = "Provides technical leadership and architecture guidance",
                            MaxSalary = 200000m,
                            MinSalary = 120000m,
                            Title = "Technical Lead"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
