// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OrgManager;

#nullable disable

namespace OrgManager.Migrations
{
    [DbContext(typeof(OrgDbContext))]
    [Migration("20250909151126_AddDepartments")]
    partial class AddDepartments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OrgManager.Controllers.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1becb0c4-4852-46e8-a05d-d46c7cf8e162"),
                            Description = "need datascience dev only",
                            Name = "Data Science"
                        },
                        new
                        {
                            Id = new Guid("6ffc9a92-8266-49a0-8d3d-1b47169be295"),
                            Description = "need fullstack dev only",
                            Name = "Full Stack"
                        },
                        new
                        {
                            Id = new Guid("c26340d5-41d1-407e-95f3-e970ae41cefe"),
                            Description = "need frontend dev only",
                            Name = "Front End"
                        },
                        new
                        {
                            Id = new Guid("7ffd8a16-eb05-429d-a9a5-672229e74443"),
                            Description = "need backend dev only",
                            Name = "Back End"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
